<?php

return [
    'currencies' => [
        [
            'name' => 'Bitcoin',
            'symbol' => 'BTC',
            'type' => 'coin',
            'decimals' => 8,
            'file_id' => '',
            'contract' => '',
            'status' => true,
            'deposit_status' => true,
            'withdraw_status' => true,
            'deposit_fee' => 0,
            'withdraw_fee' => 0.0000050,
            'min_deposit' => 0.0002,
            'max_deposit' => 0,
            'min_withdraw' => 0.0002,
            'max_withdraw' => 0,
            'min_deposit_confirmation' => 1,
            'has_payment_id' => false,
            'txn_explorer' => 'https://www.blockchain.com/btc/tx/%txid%',
        ],
        [
            'name' => 'Ethereum',
            'symbol' => 'ETH',
            'type' => 'coin',
            'decimals' => 8,
            'file_id' => '',
            'contract' => '',
            'status' => true,
            'deposit_status' => true,
            'withdraw_status' => true,
            'deposit_fee' => 0,
            'withdraw_fee' => 0.01,
            'min_deposit' => 0.0098,
            'max_deposit' => 0,
            'min_withdraw' => 0.0098,
            'max_withdraw' => 0,
            'min_deposit_confirmation' => 5,
            'has_payment_id' => false,
            'txn_explorer' => 'https://etherscan.io/tx/%txid%',
        ],
        [
            'name' => 'Ethereum',
            'symbol' => 'USDT',
            'type' => 'coin',
            'decimals' => 8,
            'file_id' => '',
            'contract' => '',
            'status' => true,
            'deposit_status' => true,
            'withdraw_status' => true,
            'deposit_fee' => 0,
            'withdraw_fee' => 0.01,
            'min_deposit' => 0.0098,
            'max_deposit' => 0,
            'min_withdraw' => 0.0098,
            'max_withdraw' => 0,
            'min_deposit_confirmation' => 5,
            'has_payment_id' => false,
            'txn_explorer' => 'https://etherscan.io/tx/%txid%',
        ]
    ],
];
